import Head from 'next/head'
import { Stack, Container, Col, Row } from "react-bootstrap";
import Button from "react-bootstrap/Button";
import Form from "react-bootstrap/Form";
import { useState, useEffect } from 'react';
import Link from 'next/link';

export default function Home() {
  function simulateNetworkRequest() {
    return new Promise((resolve) => setTimeout(resolve, 2000));
  }

  const [isLoading, setLoading] = useState(false);

  useEffect(() => {
    if (isLoading) {
      simulateNetworkRequest().then(() => {
        setLoading(false);
      });
    }
  }, [isLoading]);

  const handleClick = () => setLoading(true);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Container fluid className="bg-484F62">
          <Row
          className="d-flex 
          justify-content-center 
          align-items-center 
          vh-100
          overflow-hidden"
          >
            <Col xs={12} md={8} lg={7} xl={6} className="vw-50">
              <Stack gap={5}>
                <h1 className="text-center text-8B97B5">Sign in</h1>
                <p className="text-center text-light">
                  Sign in and start learn effectively
                </p>
              </Stack>
              <Container>
                <Row className="d-flex justify-content-center">
                  <Col xs={12} md={10} lg={9} xl={7}>
                    <Form>
                      <Stack gap={3} className="mb-5">
                        <Form.Group controlId="formEmail">
                          <Form.Control
                            type="email"
                            placeholder="Username"
                            className="rounded-4"
                          />
                        </Form.Group>

                        <Form.Group controlId="formPassword">
                          <Form.Control
                            type="password"
                            placeholder="Password"
                            className="rounded-4"
                          />
                        </Form.Group>
                        <Form.Group
                          className="d-flex justify-content-center gap-4"
                          controlId="formCheckbox"
                        >
                          <Form.Check
                            type="checkbox"
                            label="Remember me"
                            className="text-light"
                          />
                          <a
                            href="/home"
                            className="text-828282 text-decoration-none"
                          >
                            Forgot Password?
                          </a>
                        </Form.Group>
                      </Stack>
                      <div className="d-flex justify-content-around">
                        <Button
                          variant="272727"
                          type="submit"
                          className="col-4 rounded-pill"
                          disabled={isLoading}
                          onClick={!isLoading ? handleClick : null}
                        >
                          {isLoading ? 'Loading…' : 'Login'}
                        </Button>
                        <Link  href='/register'>
                          <Button
                            variant="light"
                            type="submit"
                            className="col-4 rounded-pill"
                          >
                            Register
                          </Button>
                        </Link>
                      </div>
                    </Form>
                  </Col>
                </Row>
              </Container>
            </Col>
          </Row>
        </Container>
      </main>
    </>
  )
}
